### ISSUE TITLE
./build.sh not needed and errors

### ISSUE THREAD

**Issue by gmaruzz** [sipcapture/sipgrep#16]
Thanks for wonderful work!

The README.md says you must run ./build.sh before ./configure, to compile from git clone.

I found ./build.sh errors out, does not work, and is not needed.

You can clone from git, run ./configure and then compile, whitout build.sh, and it works.

Thanks again,

-giovanni

**Comment by gmaruzz** [comment]
(on Debian 8, Jessie)

**Comment by adubovikov** [comment]
of course you can just run configure and compile, but sometimes you have to create new configure and this exactly does build.sh. Please open the build.sh and you will see.

**Comment by gmaruzz** [comment]
As you prefer, but build.sh gives errors, and one (like me) would think it cannot go on and configure.

Maybe you want to modify README.md, and add a line on it?

This what happens if I execute build.sh on Debian 8:

root@vz125:/usr/src/sipgrep# ./build.sh 
You need to have m4, automake, autoconf, libtool...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.in: You should verify that configure.in invokes AM_INIT_AUTOMAKE,
configure.in: that aclocal.m4 is present in the top-level directory,
configure.in: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
root@vz125:/usr/src/sipgrep#

**Comment by adubovikov** [comment]
this is something different, isn't ? 

check the last git, i have just fixed AM_INIT_AUTOMAKE

**Comment by gmaruzz** [comment]
Just tested with latest git 
commit f071a354affefb29a4f3ddbe060c7ed93bd8ff28
Author: Alexandr Dubovikov <alexandr.dubovikov@gmail.com>
Date:   Sat May 16 16:42:54 2015 +0200

    Update configure.in
    
    added AM_INIT to avoid errors on Debian 8

And it still give errors that can be confusing:

root@vz125:/usr/src/sipgrep# ./build.sh
You need to have m4, automake, autoconf, libtool...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
automake: error: no 'Makefile.am' found for any configure output
configure.in:18: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.in:18: the top level
root@vz125:/usr/src/sipgrep#

**Comment by adubovikov** [comment]
ok, check now

**Comment by gmaruzz** [comment]
latest:
root@vz125:/usr/src/sipgrep# ./build.sh
You need to have m4, automake, autoconf, libtool...
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
automake: error: no 'Makefile.am' found for any configure output
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
root@vz125:/usr/src/sipgrep#

**Comment by adubovikov** [comment]
ok, currently should be only warning, but the configure have to be generated ;-) I hope

**Comment by gmaruzz** [comment]
to be completely sure, I removed the sources and recloned from scratch with latest. Still give errors, unfortunately :(:

root@vz125:/usr/src/sipgrep# ./build.sh 
You need to have m4, automake, autoconf, libtool...
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:18: installing './compile'
configure.ac:11: installing './missing'
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
root@vz125:/usr/src/sipgrep#

**Comment by gmaruzz** [comment]
configure is generated correctly, but you can see the errors.

I believe best is to update the README.md and just write to ignore build.sh errors ;).

-giovanni

**Comment by adubovikov** [comment]
no, i will fix it :-) but only on this Monday, currently i don't have debian 8 here.
anyway, thank you for the report!

**Comment by gmaruzz** [comment]
No problem, thank you for your work.
Btw, I sent you mail on your gmail account.
Please check it when you have time.
Have a nice weekend.

**Comment by adubovikov** [comment]
i am replying just now :-) if you can wait 5 minutes it will be fine :-)

**Comment by gmaruzz** [comment]
:)

**Comment by jazzl0ver** [comment]
just confirming that I have same errors on the latest CentOS 6 with the latest sources

**Comment by mvenkatesh431** [comment]
Unable to build the sipgrep.
Here is the errors.

root@Venkey:/usr/src/sipgrep# ./build.sh
You need to have m4, automake, autoconf, libtool...
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1
configure.ac:20: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1857: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:20: the top level

**Comment by adubovikov** [comment]
please provide:

uname -a

and
cat /etc/issue

**Comment by lmangani** [comment]
Updated README and reordered configure.ac
