### ISSUE TITLE
Can't invert the match

### ISSUE THREAD

**Issue by jazzl0ver** [sipcapture/sipgrep#17]
Hi,

I'm trying to capture all messages but OPTIONS. Here is the cmd line and the result:

# sipgrep -v 'OPTIONS'
interface: eth0 (172.30.3.0/255.255.255.0)
filter: (ip) and ( portrange 5060-5061) or (udp and ip[6:2] & 0x3fff != 0)
don't match: ^(OPTIONS|NOTIFY)

U 2015/05/18 16:00:24.320652 172.30.3.64:5060 -> xx.yy.172.141:5260

OPTIONS sip:my.domain.com:5260 SIP/2.0.
....

# sipgrep -CV
sipgrep: V2.1.0-dev

Please, help.

**Comment by adubovikov** [comment]
please check.
608c72594335ac820a99ff613eb282811e2f9529
