### ISSUE TITLE
FTBFS on arm64

### ISSUE THREAD

**Issue by linuxmaniac** [sipcapture/sipgrep#21]
From Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802711
Reported by: Edmund Grimley Evans

It failed to build on arm64:

https://buildd.debian.org/status/package.php?p=sipgrep&suite=sid

The error was:
```
tcpreasm.o: In function `tcpreasm_ip_next_tcp':
/«PKGBUILDDIR»/tcpreasm.c:244:(.text+0x200): relocation truncated to fit: R_AARCH64_LDST32_ABS_LO12_NC against symbol `debug' defined in .bss section in sipgrep.o
```
This is presumably because "debug" is declared with different types in
the two files:
```
sipgrep.c:uint8_t debug = 0;
tcpreasm.c:extern int debug;
```
You should be grateful to the arm64 tool chain for providing such a
succinct diagnostic message!

**Comment by adubovikov** [comment]
thanks for bug report. 

fixed:

https://github.com/sipcapture/sipgrep/commit/a791b051a4e45453032b70924f73c0a0b369be0b
