### ISSUE TITLE
Sipgrep tool unable to dump packets from any other ports other then 5060-5061

### ISSUE THREAD

**Issue by siju-irs** [sipcapture/sipgrep#22]
Hi Team,
I am using sipgrep tool to capture sip packets for debugging. I could notice that this tool is unable to capture packets from any other different ports other then default ports. I used to below command for the same... 
sipgrep -f *********** -P 5062
i got the response as below...
eth0: no IPv4 address assigned: Cannot assign requested address
interface: eth0
filter: (ip) and ( portrange 5062) or (udp and ip[6:2] & 0x3fff != 0)
match: (From:|f:) (.*)************(.*)

Please advice me how the capture packets of different ports other then default ports through sipgrep.

**Comment by adubovikov** [comment]
Hi,

you do all correct. This is just notification, please ignore

**Comment by siju-irs** [comment]
wonder, if there any way to capture the packets from other ports using sipgrep?

**Comment by adubovikov** [comment]
again, you should use -P flag for this:

i.e. get all packets from port 5090 up to 5092:

sipgrep -P 5090-5092

**Comment by lmangani** [comment]
@siju-irs the portrange parameter requires a range, you specified a single value in your example
<pre>filter: (ip) and ( portrange 5062) or (udp and ip[6:2] & 0x3fff != 0)</pre>

**Comment by svarunan** [comment]
Hi Siju thanks for asking this!

Hi @lmangani and @adubovikov , Here are my findings  now.
I use a javascript phone client like JSsip and sipJS, which communicates with VOIP server over websocket ws for inbound and outbound connections. WS is pure TCP, so i guess its not working here in SIPGREP. 

Does sipgrep supports tcp as optional?

**Comment by adubovikov** [comment]
yes, it does.

**Comment by lmangani** [comment]
Not sure if this is interesting for your purpose, but you can also have the JS client "intercept itself" using our HEP/EEP JS encoder to send encapsulated signaling and/or internal code logs possibly providing an on-demand remote capture/debug functionality without a sniffer for development cases

**Comment by siju-irs** [comment]
Hi @lmangani @adubovikov,
the above solution is working fine but do you guys have solution for svarunan's query..?

**Comment by lmangani** [comment]
@siju-irs Yes, we answered both inquiries

**Comment by svarunan** [comment]
@lmangani please correct me if i'm wrong. I don't find an option to capture tcp in --help section.

**Comment by adubovikov** [comment]
the default capturing is by ip (includes tcp and udp protocols)
