### ISSUE TITLE
fatal: unsupported interface type 113

### ISSUE THREAD

**Issue by ultraboby** [sipcapture/sipgrep#26]
I start sipgrep with folowing command:

sipgrep -d any '^(INVITE|INFO)' -P 5060-5080

sipgrep: V2.2.0
CentOS Linux release 7.1.1503
libpcap-1.5.3-8.el7.x86_64

**Comment by adubovikov** [comment]
can you please install lipcap-dev as well ?

**Comment by ultraboby** [comment]
libpcap-devel-1.5.3-8.el7.x86_64 already installed and latest version

**Comment by adubovikov** [comment]
can you do:
grep -R DLT_LINUX_SLL /usr/include/

and show a result

**Comment by ultraboby** [comment]
/usr/include/pcap/sll.h: * handle DLT_LINUX_SLL captures will continue to handle them correctly
/usr/include/pcap/sll.h: * A DLT_LINUX_SLL fake link-layer header.
/usr/include/pcap/bpf.h: * sometimes it isn't.)  We currently handle it as DLT_LINUX_SLL,
/usr/include/pcap/bpf.h:#define DLT_LINUX_SLL   113

**Comment by adubovikov** [comment]
and in the source directory after configure can you do "grep HAVE_DLT_LINUX_SLL
*.log"

**Comment by adubovikov** [comment]
sorry:
grep HAVE_DLT_LINUX_SLL *.h

**Comment by ultraboby** [comment]
nothing ?!

**Comment by adubovikov** [comment]
as workaround, please add to config.h

#define HAVE_DLT_LINUX_SLL 1

**Comment by ultraboby** [comment]
no difference

**Comment by adubovikov** [comment]
weird
ok, please add this as additional string to the config.h

#define DLT_LINUX_SLL 113

**Comment by ultraboby** [comment]
the same error ..

**Comment by adubovikov** [comment]
you do something wrong, because this is only things that generate the error.
if the parameters has been defined , the error should be disappeared.

you can put these parameters to the sipgrep.c and try again.

**Comment by ultraboby** [comment]
sorry but this not work in my server ..

**Comment by ultraboby** [comment]
The same problem on centos 6.7 fresh install ..

**Comment by lmangani** [comment]
reproduced, standby for a patch

**Comment by adubovikov** [comment]
can you please try again ?
get the last git

**Comment by ultraboby** [comment]
It's OK now. 

Thank you!

**Comment by wolfru68** [comment]
There was the same error when collecting.
[root@kv-dkweb-02 sipgrep-master]# make
Making all in src
make[1]: Entering directory `/home/toor/SRC/sipgrep-master/src'
make  all-am
make[2]: Entering directory `/home/toor/SRC/sipgrep-master/src'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipgrep.o -MD -MP -MF .deps/sipgrep.Tpo -c -o sipgrep.o sipgrep.c
mv -f .deps/sipgrep.Tpo .deps/sipgrep.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT log.o -MD -MP -MF .deps/log.Tpo -c -o log.o log.c
mv -f .deps/log.Tpo .deps/log.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT ipreasm.o -MD -MP -MF .deps/ipreasm.Tpo -c -o ipreasm.o ipreasm.c
mv -f .deps/ipreasm.Tpo .deps/ipreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT tcpreasm.o -MD -MP -MF .deps/tcpreasm.Tpo -c -o tcpreasm.o tcpreasm.c
mv -f .deps/tcpreasm.Tpo .deps/tcpreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipparse.o -MD -MP -MF .deps/sipparse.Tpo -c -o sipparse.o sipparse.c
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipparse.o -MD -MP -MF .deps/sipparse.Tpo -c -o sipparse.o sipparse.c
sipparse.c: In function ‘set_hname’:
sipparse.c:43:12: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   for (; s < end; s++) {
            ^
mv -f .deps/sipparse.Tpo .deps/sipparse.Po
[root@kv-dkweb-02 sipgrep-master]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

**Comment by adubovikov** [comment]
sorry, I don't see any error, only warning... can you be a bit more specific ?

**Comment by wolfru68** [comment]
[root@kv-dkweb-02 sipgrep-master]# script make.script
Script started, file is make.script
[root@kv-dkweb-02 sipgrep-master]# make
Making all in src
make[1]: Entering directory `/home/toor/SRC/sipgrep-master/src'
make  all-am
make[2]: Entering directory `/home/toor/SRC/sipgrep-master/src'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipgrep.o -MD -MP -MF .deps/sipgrep.Tpo -c -o sipgrep.o sipgrep.c
mv -f .deps/sipgrep.Tpo .deps/sipgrep.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT log.o -MD -MP -MF .deps/log.Tpo -c -o log.o log.c
mv -f .deps/log.Tpo .deps/log.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT ipreasm.o -MD -MP -MF .deps/ipreasm.Tpo -c -o ipreasm.o ipreasm.c
mv -f .deps/ipreasm.Tpo .deps/ipreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT tcpreasm.o -MD -MP -MF .deps/tcpreasm.Tpo -c -o tcpreasm.o tcpreasm.c
mv -f .deps/tcpreasm.Tpo .deps/tcpreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipparse.o -MD -MP -MF .deps/sipparse.Tpo -c -o sipparse.o sipparse.c
sipparse.c: In function ‘set_hname’:
sipparse.c:43:12: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   for (; s < end; s++) {
            ^
mv -f .deps/sipparse.Tpo .deps/sipparse.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT transport_hep.o -MD -MP -MF .deps/transport_hep.Tpo -c -o transport_hep.o transport_hep.c
mv -f .deps/transport_hep.Tpo .deps/transport_hep.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o sipgrep sipgrep.o log.o ipreasm.o tcpreasm.o sipparse.o transport_hep.o   -lpcre -lpcap -ldl -lpthread
libtool: link: gcc -g -O2 -o sipgrep sipgrep.o log.o ipreasm.o tcpreasm.o sipparse.o transport_hep.o  -lpcre -lpcap -ldl -lpthread
make[2]: Leaving directory `/home/toor/SRC/sipgrep-master/src'
make[1]: Leaving directory `/home/toor/SRC/sipgrep-master/src'
make[1]: Entering directory `/home/toor/SRC/sipgrep-master'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/toor/SRC/sipgrep-master'
[root@kv-dkweb-02 sipgrep-master]# man sgrep
No manual entry for sgrep
[root@kv-dkweb-02 sipgrep-master]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

**Comment by wolfru68** [comment]
[root@kv-dkweb-02 sipgrep-master]# ./build.sh
You need to have m4, automake, autoconf, libtool...
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:5: installing './missing'
src/Makefile.am: installing './depcomp'
[root@kv-dkweb-02 sipgrep-master]# ./configure
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to use compression... no
checking whether to use ssl... no
checking whether to use ncurses... no
checking whether to use redis... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking for pcap_open_live in -lpcap... yes
configure: checking for pcre Library and Header files...
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for pcre_compile in -lpcre... yes
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking for int32_t... yes
checking for int8_t... yes
checking for pid_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for gettimeofday... yes
checking for memset... yes
checking for select... yes
checking for socket... yes
checking for strdup... yes
checking for strerror... yes
checking for strndup... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

sipgrep 2.2.1

Build directory............. :
Installation prefix......... : /usr/local
IPv6 support.................: no
HEP support................. : yes
HEP Compression............. : no
SSL/TLS..................... : no
Ncurses support............. : no

Build with REDIS............ : no
Build with PCRE............. : yes

[root@kv-dkweb-02 sipgrep-master]# make
Making all in src
make[1]: Entering directory `/home/toor/SRC/sipgrep-master/src'
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/sh /home/toor/SRC/sipgrep-master/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd .. && /bin/sh ./config.status src/config.h
config.status: creating src/config.h
config.status: src/config.h is unchanged
make  all-am
make[2]: Entering directory `/home/toor/SRC/sipgrep-master/src'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipgrep.o -MD -MP -MF .deps/sipgrep.Tpo -c -o sipgrep.o sipgrep.c
mv -f .deps/sipgrep.Tpo .deps/sipgrep.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT log.o -MD -MP -MF .deps/log.Tpo -c -o log.o log.c
mv -f .deps/log.Tpo .deps/log.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT ipreasm.o -MD -MP -MF .deps/ipreasm.Tpo -c -o ipreasm.o ipreasm.c
mv -f .deps/ipreasm.Tpo .deps/ipreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT tcpreasm.o -MD -MP -MF .deps/tcpreasm.Tpo -c -o tcpreasm.o tcpreasm.c
mv -f .deps/tcpreasm.Tpo .deps/tcpreasm.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT sipparse.o -MD -MP -MF .deps/sipparse.Tpo -c -o sipparse.o sipparse.c
sipparse.c: In function ‘set_hname’:
sipparse.c:43:12: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   for (; s < end; s++) {
            ^
mv -f .deps/sipparse.Tpo .deps/sipparse.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT transport_hep.o -MD -MP -MF .deps/transport_hep.Tpo -c -o transport_hep.o transport_hep.c
mv -f .deps/transport_hep.Tpo .deps/transport_hep.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o sipgrep sipgrep.o log.o ipreasm.o tcpreasm.o sipparse.o transport_hep.o   -lpcre -lpcap -ldl -lpthread
libtool: link: gcc -g -O2 -o sipgrep sipgrep.o log.o ipreasm.o tcpreasm.o sipparse.o transport_hep.o  -lpcre -lpcap -ldl -lpthread
make[2]: Leaving directory `/home/toor/SRC/sipgrep-master/src'
make[1]: Leaving directory `/home/toor/SRC/sipgrep-master/src'
make[1]: Entering directory `/home/toor/SRC/sipgrep-master'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/toor/SRC/sipgrep-master'
[root@kv-dkweb-02 sipgrep-master]#

**Comment by wolfru68** [comment]
I tell that there is an error when compiling the code. I can remove the protocol if it is not needed.

**Comment by adubovikov** [comment]
I dont see any error , can you be more specific ?

**Comment by wolfru68** [comment]
make 
perceives as an error and the compilation stops there
