### ISSUE TITLE
Cannot show RTCP stats

### ISSUE THREAD

**Issue by kisienya** [sipcapture/sipgrep#32]
Much appreciate this tool.

I have configured my Asterisk according to 
https://github.com/sipcapture/homer/wiki/Examples%3A-Asterisk

SIP Signaling works correctly but there are RTCP STATS when I run sipgrep.

In essence I am not getting quality of service stats.

Kindly assist.

Regards

**Comment by adubovikov** [comment]
@kisienya please open the issue in the Homer repository. 

thank you

**Comment by kisienya** [comment]
Ok thanks will fo that
