### ISSUE TITLE
 A memory leak may occur

### ISSUE THREAD

**Issue by hclonej** [sipcapture/sipgrep#36]
https://github.com/sipcapture/sipgrep/blob/c974e75381bd55196a939a37bec369e3b14d06c4/src/sipgrep.c#L1304

This line seems unnecessary.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/sipgrep/commit/1cc00079cd80310f7e8b1a696e9a02b8a2b25e04

than you!
