### ISSUE TITLE
Why is the traffic high?

### ISSUE THREAD

**Issue by daxiondi** [sipcapture/sipgrep#41]
Using sipgrep to send homer traffic, the export bandwidth will suddenly increase. What is causing this? Is there any way to avoid it?

![image](https://user-images.githubusercontent.com/26639571/127123647-d143d212-f4ca-485c-bc65-1f54a5489b3b.png)

**Comment by lmangani** [comment]
An HEP client should only send what it receives - so something is on the wire - could you confirm you're not being scanned or something? If this is the case, You should see what happened in the protocol statistics quite clearly.

Side note: sipgrep is not an agent designed for perpetual mirroring and rather for casual console usage.
I would suggest using a proper agent designed for the job, such as heplify or captagent to confirm if this happens there too.

**Comment by daxiondi** [comment]
I use sngrep, there is no such situation, confirm that it has not been scanned

**Comment by lmangani** [comment]
@daxiondi I can tell you use sngrep, the question is why sipgrep instead of a dedicated agent?
Is this a "one-off" type of capture or permanently running?

**Comment by daxiondi** [comment]
I hope it will run permanently, and I can view the history of SIP signaling on homer

**Comment by lmangani** [comment]
@daxiondi please switch to [heplify](https://github.com/sipcapture/heplify) if you are running a perpetual sniffer.

**Comment by daxiondi** [comment]
I will try and tell you to use the report

**Comment by daxiondi** [comment]
It's been used for some time. Duplicate is really easy to use and stable. Thank you
